# Generated by Django 3.1 on 2020-08-27 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanset_name', models.CharField(max_length=250)),
                ('scan_every_min', models.IntegerField()),
                ('scan_every_days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ScanTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=250)),
                ('scan_options', models.CharField(max_length=250)),
                ('scan_script', models.CharField(max_length=250)),
                ('output_format', models.CharField(choices=[('XM', 'XML'), ('LS', 'LOGSTASH')], default='XML', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='SiteAssest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=250)),
                ('location_name', models.CharField(max_length=250)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('site_ip_range1', models.CharField(blank=True, max_length=250)),
                ('site_ip_range2', models.CharField(blank=True, max_length=250)),
                ('site_ip_range3', models.CharField(blank=True, max_length=250)),
                ('last_scaned', models.DateField()),
                ('current_status', models.CharField(choices=[('ID', 'IDLE'), ('RU', 'RUNNING')], default='IDLE', max_length=2)),
                ('site_rank', models.IntegerField()),
                ('scan_count', models.IntegerField(default=0)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='scanmodule.scanset')),
            ],
        ),
        migrations.AddField(
            model_name='scanset',
            name='scan_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='scanmodule.scantemplate'),
        ),
    ]
