# Generated by Django 3.1 on 2020-08-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanmodule', '0002_auto_20200823_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='images/usersdef_user.png', upload_to='images/users'),
        ),
    ]
