# Generated by Django 3.2.4 on 2021-06-20 14:27

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scanmodule', '0003_auto_20210620_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostscanned',
            old_name='site_name',
            new_name='scan_name',
        ),
        migrations.AddField(
            model_name='scanhistory',
            name='scan_name',
            field=models.CharField(blank=True, default='DEF', max_length=250),
        ),
        migrations.AddField(
            model_name='siteassest',
            name='scan_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siteassest',
            name='scan_time_end',
            field=models.DateTimeField(default=datetime.date(2021, 6, 20)),
        ),
        migrations.AlterField(
            model_name='siteassest',
            name='scan_time_start',
            field=models.DateTimeField(default=datetime.date(2021, 6, 20)),
        ),
    ]
