# Generated by Django 3.2.4 on 2021-07-10 19:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scanmodule', '0004_auto_20210620_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostosscanned',
            name='host_ip_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanmodule.hostscanned'),
        ),
        migrations.AlterField(
            model_name='portdiscovery',
            name='host_ip_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanmodule.hostscanned'),
        ),
        migrations.AlterField(
            model_name='siteassest',
            name='scan_time_end',
            field=models.DateTimeField(default=datetime.date(2021, 7, 10)),
        ),
        migrations.AlterField(
            model_name='siteassest',
            name='scan_time_start',
            field=models.DateTimeField(default=datetime.date(2021, 7, 10)),
        ),
    ]
