# Generated by Django 3.2.5 on 2021-07-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanmodule', '0007_alter_hostscanned_host_ip_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostscanned',
            name='host_ip_name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
