# Generated by Django 3.2.5 on 2021-08-05 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanmodule', '0008_alter_hostscanned_host_ip_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteassest',
            name='scan_time_end',
            field=models.DateTimeField(default=datetime.date(2021, 8, 5)),
        ),
        migrations.AlterField(
            model_name='siteassest',
            name='scan_time_start',
            field=models.DateTimeField(default=datetime.date(2021, 8, 5)),
        ),
    ]
