# Generated by Django 3.2.5 on 2021-08-07 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanmodule', '0009_auto_20210805_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteassest',
            name='last_scaned',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='siteassest',
            name='scan_time_end',
            field=models.DateTimeField(default=datetime.date(2021, 8, 7)),
        ),
        migrations.AlterField(
            model_name='siteassest',
            name='scan_time_start',
            field=models.DateTimeField(default=datetime.date(2021, 8, 7)),
        ),
        migrations.AlterField(
            model_name='siteassest',
            name='site_rank',
            field=models.IntegerField(blank=True),
        ),
    ]
