# Generated by Django 3.2.5 on 2021-08-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanmodule', '0010_auto_20210807_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteassest',
            name='last_scaned',
            field=models.DateField(null=True),
        ),
    ]
