# Generated by Django 3.2.5 on 2021-08-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanmodule', '0011_alter_siteassest_last_scaned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteassest',
            name='site_rank',
            field=models.IntegerField(null=True),
        ),
    ]
