# Generated by Django 3.2.5 on 2021-08-14 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanmodule', '0012_alter_siteassest_site_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostosscanned',
            name='os_cpe',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='hostosscanned',
            name='os_family',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hostosscanned',
            name='os_fingerprint',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='hostosscanned',
            name='os_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='hostosscanned',
            name='os_vendor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='siteassest',
            name='scan_time_end',
            field=models.DateTimeField(default=datetime.date(2021, 8, 14)),
        ),
        migrations.AlterField(
            model_name='siteassest',
            name='scan_time_start',
            field=models.DateTimeField(default=datetime.date(2021, 8, 14)),
        ),
    ]
